#!/bin/bash

# Uses bash environment variables, but you can switch them to hard-coded paths
# if you prefer.
driverDocs=$glpu_driver_docs          # update to driver path
libDocs=$glpu_efun_docs         # update to mudlib path

types=("apply" "efun")    # exclude concepts, driver, stdlib, and zh-CN

for type in ${types[@]} ; do
    mkdir -p ${libDocs}/${type} # ensure mudlib dir exists

echo "New dir = ${libDocs}/${type}"

    for dir in ${driverDocs}/${type}/* ; do
        for file in ${dir}/*.md ; do
            filename=${file##*/}    # grab everything after last /

            [[ ${filename} =~ ^__ ]] && continue    # ignore obsolete apply __INIT
            [[ ${filename} =~ ^README ]] && continue    # ignore README
            [[ ${filename} == index.md ]] && continue    # ignore index

            # new doc file path
            newDoc=${libDocs}/${type}/${filename%.md}
            echo "Processing ${newDoc}"

            cp ${file} ${newDoc}            # copy file
            sed -i '1,5 d' ${newDoc}        # trim beginning of file
            sed -i '/^#\s+${filename}\s*$/d' ${newDoc} # remove title
            sed -i '/```\(c\|\)\s*$/d' ${newDoc}  # remove C code block tags
        done
    done
done
