#ifndef __DAEMONS_H__
#define __DAEMONS_H__

#include <dirs.h>

#define ACTION_D        DIR_DAEMONS "action"
#define ADVANCE_D       DIR_DAEMONS "advance"
#define ALARM_D         DIR_DAEMONS "alarm"
#define AUTODOC_D       DIR_DAEMONS "autodoc"
#define BANK_D          DIR_DAEMONS "bank"
#define BODY_D          DIR_DAEMONS "body"
#define BOOT_D          DIR_DAEMONS "boot"
#define CHAN_D          DIR_DAEMONS "chan_d"
#define COLOUR_D        DIR_DAEMONS "colour"
#define CONFIG_D        DIR_DAEMONS "config"
#define CRASH_D         DIR_DAEMONS "crash"
#define CURRENCY_D      DIR_DAEMONS "currency"
#define DB_D            DIR_DAEMONS "db"
#define DEATH_D         DIR_DAEMONS "death"
#define FINGER_D        DIR_DAEMONS "finger_d"
#define GA_SERVER       DIR_DAEMONS "ga_server"
#define GH_ISSUES_D     DIR_DAEMONS "github_issues"
#define GMCP_D          DIR_DAEMONS "gmcp"
#define GRAPEVINE_D     DIR_DAEMONS "grapevine"
#define HTTPC_D         DIR_DAEMONS "httpc"
#define LINES_D         DIR_DAEMONS "lines"
#define LOCKDOWN_D      DIR_DAEMONS "lockdown_d"
#define LOOT_D          DIR_DAEMONS "loot"
#define MAIL_D          DIR_DAEMONS "mail_d"
#define MESS_D          DIR_DAEMONS "message"
#define MOVE_D          DIR_DAEMONS "movement"
#define MSSP_D          DIR_DAEMONS "mssp"
#define MUDDY_D         DIR_DAEMONS "muddy"
#define NEWS_D          DIR_DAEMONS "news_d"
#define PERLIN_D        DIR_DAEMONS "perlin"
#define PERSIST_D       DIR_DAEMONS "persist"
#define RECURSE_RMDIR_D DIR_DAEMONS "recurse_rmdir"
#define SHUTDOWN_D      DIR_DAEMONS "shutdown"
#define SIGNAL_D        DIR_DAEMONS "signal"
#define SOUL_D          DIR_DAEMONS "soul_d"
#define SWAP_D          DIR_DAEMONS "swap"
#define TIME_D          DIR_DAEMONS "time"
#define VIRTUAL_D       DIR_DAEMONS "virtual"
#define WEBSOCKET_D     DIR_DAEMONS "websocket_client"

#endif // __DAEMONS_H__
