// discord_events.h

#ifndef DISCORD_H
#define DISCORD_H

#include <websocket.h>
#include <discord_intents.h>

// Discord opcodes
#define DISCORD_DISPATCH 0x00
#define DISCORD_HEARTBEAT 0x01
#define DISCORD_IDENTIFY 0x02
#define DISCORD_PRESENCE_UPDATE 0x03
#define DISCORD_VOICE_STATE_UPDATE 0x04
#define DISCORD_RESUME 0x06
#define DISCORD_RECONNECT 0x07
#define DISCORD_REQUEST_GUILD_MEMBERS 0x08
#define DISCORD_INVALID_SESSION 0x09
#define DISCORD_HELLO 0x0A
#define DISCORD_HEARTBEAT_ACK 0x0B

// Discord events
#define EVENT_READY "READY"
#define EVENT_MESSAGE_CREATE "MESSAGE_CREATE"
#define EVENT_GUILD_CREATE "GUILD_CREATE"
#define EVENT_GUILD_DELETE "GUILD_DELETE"
#define EVENT_CHANNEL_CREATE "CHANNEL_CREATE"
#define EVENT_CHANNEL_DELETE "CHANNEL_DELETE"
#define EVENT_GUILD_MEMBER_ADD "GUILD_MEMBER_ADD"
#define EVENT_GUILD_MEMBER_REMOVE "GUILD_MEMBER_REMOVE"
#define EVENT_MESSAGE_UPDATE "MESSAGE_UPDATE"
#define EVENT_MESSAGE_DELETE "MESSAGE_DELETE"
#define EVENT_PRESENCE_UPDATE "PRESENCE_UPDATE"
#define EVENT_TYPING_START "TYPING_START"

// Discord-specific close codes
#define DISCORD_CLOSE_UNKNOWN_ERROR 4000
#define DISCORD_CLOSE_UNKNOWN_OPCODE 4001
#define DISCORD_CLOSE_DECODE_ERROR 4002
#define DISCORD_CLOSE_NOT_AUTHENTICATED 4003
#define DISCORD_CLOSE_AUTHENTICATION_FAILED 4004
#define DISCORD_CLOSE_ALREADY_AUTHENTICATED 4005
#define DISCORD_CLOSE_INVALID_SEQUENCE 4007
#define DISCORD_CLOSE_RATE_LIMITED 4008
#define DISCORD_CLOSE_SESSION_TIMED_OUT 4009
#define DISCORD_CLOSE_INVALID_SHARD 4010
#define DISCORD_CLOSE_SHARDING_REQUIRED 4011
#define DISCORD_CLOSE_INVALID_API_VERSION 4012
#define DISCORD_CLOSE_INVALID_INTENTS 4013
#define DISCORD_CLOSE_DISALLOWED_INTENTS 4014

#endif // DISCORD_H
