#ifndef __GMCP_DEFINES_H__
#define __GMCP_DEFINES_H__

// Packages, subpackges, and commands
#define GMCP_PKG_CORE                       "Core"
#define GMCP_PKG_CORE_HELLO                 GMCP_PKG_CORE".Hello"
#define GMCP_PKG_CORE_PING                  GMCP_PKG_CORE".Ping"
#define GMCP_PKG_CORE_SUPPORTS              GMCP_PKG_CORE".Supports"

#define GMCP_PKG_CHAR                       "Char"
#define GMCP_PKG_CHAR_STATUS                GMCP_PKG_CHAR".Status"
#define GMCP_PKG_CHAR_STATUSVARS            GMCP_PKG_CHAR".StatusVars"
#define GMCP_PKG_CHAR_VITALS                GMCP_PKG_CHAR".Vitals"
#define GMCP_PKG_CHAR_LOGIN                 GMCP_PKG_CHAR".Login"
#define GMCP_PKG_CHAR_LOGIN_DEFAULT         GMCP_PKG_CHAR_LOGIN".Default"
#define GMCP_PKG_CHAR_LOGIN_CREDENTIALS     GMCP_PKG_CHAR_LOGIN".Credentials"
#define GMCP_PKG_CHAR_LOGIN_RESULT          GMCP_PKG_CHAR_LOGIN".Result"

#define GMCP_PKG_COMM                       "Comm"
#define GMCP_PKG_COMM_CHANNEL               GMCP_PKG_COMM".Channel"
#define GMCP_PKG_COMM_CHANNEL_LIST          GMCP_PKG_COMM_CHANNEL".List"
#define GMCP_PKG_COMM_CHANNEL_TEXT          GMCP_PKG_COMM_CHANNEL".Text"

#define GMCP_PKG_EXTERNAL                    "External"
#define GMCP_PKG_EXTERNAL_DISCORD            GMCP_PKG_EXTERNAL".Discord"
#define GMCP_PKG_EXTERNAL_DISCORD_HELLO      GMCP_PKG_EXTERNAL_DISCORD".Hello"
#define GMCP_PKG_EXTERNAL_DISCORD_GET        GMCP_PKG_EXTERNAL_DISCORD".Get"

#define GMCP_PKG_CLIENT                      "Client"
#define GMCP_PKG_CLIENT_GUI                  GMCP_PKG_CLIENT".GUI"
#define GMCP_PKG_CLIENT_GUI_INSTALL          GMCP_PKG_CLIENT_GUI".Install"

// Labels and display values
#define GMCP_LBL_CHAR_STATUS_NAME           "name"
#define GMCP_DIS_CHAR_STATUS_NAME           "Name"
#define GMCP_LBL_CHAR_STATUS_XP             "xp"
#define GMCP_DIS_CHAR_STATUS_XP             "XP"
#define GMCP_LBL_CHAR_STATUS_TNL            "tnl"
#define GMCP_DIS_CHAR_STATUS_TNL            "TNL"
#define GMCP_LBL_CHAR_STATUS_LEVEL          "level"
#define GMCP_DIS_CHAR_STATUS_LEVEL          "Level"
#define GMCP_LBL_CHAR_STATUS_FILL           "fill"
#define GMCP_DIS_CHAR_STATUS_FILL           "Fill"
#define GMCP_LBL_CHAR_STATUS_CAPACITY       "capacity"
#define GMCP_DIS_CHAR_STATUS_CAPACITY       "Capacity"
#define GMCP_LBL_CHAR_STATUS_CURRENT_ENEMY  "current_enemy"
#define GMCP_DIS_CHAR_STATUS_CURRENT_ENEMY  "Current Enemy"
#define GMCP_LBL_CHAR_STATUS_CURRENT_ENEMY_HEALTH "current_enemy_health"
#define GMCP_DIS_CHAR_STATUS_CURRENT_ENEMY_HEALTH "Current Enemy Health"
#define GMCP_LBL_CHAR_STATUS_CURRENT_ENEMIES "current_enemies"
#define GMCP_DIS_CHAR_STATUS_CURRENT_ENEMIES "Current Enemies"
#define GMCP_LBL_CHAR_STATUS_SEEN_ENEMIES   "seen_enemies"
#define GMCP_DIS_CHAR_STATUS_SEEN_ENEMIES   "Seen Enemies"
#define GMCP_LBL_CHAR_VITALS_HP             "hp"
#define GMCP_LBL_CHAR_VITALS_MAX_HP         "max_hp"
#define GMCP_LBL_CHAR_VITALS_HP_RATIO       "hp_ratio"
#define GMCP_LBL_CHAR_VITALS_SP             "sp"
#define GMCP_LBL_CHAR_VITALS_MAX_SP         "max_sp"
#define GMCP_LBL_CHAR_VITALS_SP_RATIO       "sp_ratio"
#define GMCP_LBL_CHAR_VITALS_MP             "mp"
#define GMCP_LBL_CHAR_VITALS_MAX_MP         "max_mp"
#define GMCP_LBL_CHAR_VITALS_MP_RATIO       "mp_ratio"
#define GMCP_LBL_GMCP_CLIENT_GUI_URL        "url"
#define GMCP_LBL_GMCP_CLIENT_GUI_VERSION    "version"

#define GMCP_PKG_ROOM                       "Room"
#define GMCP_PKG_ROOM_INFO                  GMCP_PKG_ROOM".Info"
#define GMCP_PKG_ROOM_TRAVEL                GMCP_PKG_ROOM".Travel"

#define GMCP_PKG_ITEM                       "Item"
#define GMCP_PKG_ITEM_LIST                 GMCP_PKG_ITEM".List"
#define GMCP_PKG_ITEM_ADD                  GMCP_PKG_ITEM".Add"
#define GMCP_PKG_ITEM_REMOVE               GMCP_PKG_ITEM".Remove"
#define GMCP_PKG_ITEM_UPDATE               GMCP_PKG_ITEM".Update"

#endif // __GMCP_DEFINES_H__
