// websocket.h

#ifndef WEBSOCKET_H
#define WEBSOCKET_H

#define WS_HANDSHAKE_GUID "258EAFA5-E914-47DA-95CA-C5AB0DC85B11"

// WebSocket states
#define WS_STATE_RESOLVING 0
#define WS_STATE_CONNECTING 1
#define WS_STATE_HANDSHAKE 2
#define WS_STATE_CONNECTED 3
#define WS_STATE_HANDSHAKE_FAILED 4
#define WS_STATE_CLOSED 5
#define WS_STATE_ERROR 100

// WebSocket opcodes
#define WS_BINARY_FRAME 0x02
#define WS_CLOSE_FRAME 0x08
#define WS_CONTINUATION_FRAME 0x00
#define WS_PING_FRAME 0x09
#define WS_PONG_FRAME 0x0A
#define WS_TEXT_FRAME 0x01

// All valid WebSocket opcodes
#define WS_VALID_FRAME_OPCODES ({ \
    WS_BINARY_FRAME, \
    WS_CLOSE_FRAME, \
    WS_CONTINUATION_FRAME, \
    WS_PING_FRAME, \
    WS_PONG_FRAME, \
    WS_TEXT_FRAME, \
})

// WebSocket close codes
#define WS_CLOSE_NORMAL 1000
#define WS_CLOSE_GOING_AWAY 1001
#define WS_CLOSE_PROTOCOL_ERROR 1002
#define WS_CLOSE_UNSUPPORTED_DATA 1003
#define WS_CLOSE_NO_STATUS_RECEIVED 1005
#define WS_CLOSE_ABNORMAL 1006
#define WS_CLOSE_INVALID_FRAME_PAYLOAD_DATA 1007
#define WS_CLOSE_POLICY_VIOLATION 1008
#define WS_CLOSE_MESSAGE_TOO_BIG 1009
#define WS_CLOSE_MANDATORY_EXTENSION 1010
#define WS_CLOSE_INTERNAL_SERVER_ERROR 1011
#define WS_CLOSE_TLS_HANDSHAKE 1015

#endif // WEBSOCKET_H
